"""Code generation: turns a ProjectSpec into working FastAPI application files.

Each `..._code(spec, ...)` returns the full text of a generated file. The
generator is intentional and small: models -> schemas -> routers -> main, plus
run/config/CI scaffolding. Everything is plain AST-free text so users can diff
and hand-edit the output.
"""
from typing import Dict, List, Optional

from .spec import ProjectSpec, ResourceSpec

# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------


def class_name(name: str) -> str:
    return "".join(p.title() for p in name.replace("-", "_").split("_"))


def env_key(project_name: str, suffix: str) -> str:
    base = project_name.upper().replace("-", "_")
    return f"{base}_{suffix}"


# SQLAlchemy column snippet per field kind
_COLUMN = {
    "string": lambda f: f"Column(String(255))",
    "text": lambda f: f"Column(Text)",
    "int": lambda f: f"Column(Integer)",
    "float": lambda f: f"Column(Float)",
    "bool": lambda f: f"Column(Boolean, default=False)",
    "date": lambda f: f"Column(Date)",
    "datetime": lambda f: f"Column(DateTime)",
    "json": lambda f: f"Column(JSON)",
    "list": lambda f: f"Column(JSON)",
    "password": lambda f: f"Column(String(256))",
}

# Pydantic type snippet per field kind
_PYD = {
    "string": "str",
    "text": "str",
    "int": "int",
    "float": "float",
    "bool": "bool",
    "date": "date",
    "datetime": "datetime",
    "json": "Any",
    "list": "List[str]",
    "password": "str",
}

_PYD_DEFAULT = {
    "list": " = []",
    "bool": " = False",
}

N = "\n"


# --------------------------------------------------------------------------
# config.py
# --------------------------------------------------------------------------


def config_code(spec: ProjectSpec) -> str:
    env_db = env_key(spec.name, "DB")
    env_sec = env_key(spec.name, "SECRET")
    return f"""# Auto-generated by ayka-kit. Edit freely.
import os
from pathlib import Path

APP_NAME = {spec.name!r}
TITLE = {spec.title!r}
VERSION = "0.1.0"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_FILE = os.environ.get({env_db!r}, os.path.join(BASE_DIR, "data", {spec.name + '.db'!r}))
SECRET_ENV = {env_sec!r}
SECRET_FILE = os.path.join(BASE_DIR, ".secret_key")
RATE_LIMIT = int(os.environ.get({env_key(spec.name, 'RATE_LIMIT')!r}, "120"))
RATE_WINDOW = 60
"""


# --------------------------------------------------------------------------
# database.py
# --------------------------------------------------------------------------


def database_code(spec: ProjectSpec) -> str:
    return """# Auto-generated by ayka-kit. Edit freely.
import os
from sqlalchemy.orm import declarative_base, sessionmaker
from ayka.db import make_engine, ensure_schema
from app import config

if config.DB_FILE != ":memory:":
    os.makedirs(os.path.dirname(config.DB_FILE) or ".", exist_ok=True)

engine = make_engine(config.DB_FILE)
SessionLocal = sessionmaker(bind=engine)
Base = declarative_base()


def init_db():
    ensure_schema(Base, engine)


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
"""


# --------------------------------------------------------------------------
# models.py
# --------------------------------------------------------------------------


def _model_body(res: ResourceSpec, spec: ProjectSpec) -> List[str]:
    lines = ["    id = Column(Integer, primary_key=True, index=True)"]
    for f in res.fields:
        if f.name in ("id", "owner_id", "created_at", "updated_at"):
            continue
        lines.append(f"    {f.name} = {_COLUMN[f.kind](f)}")
    if spec.auth and not res.public:
        lines.append(f"    owner_id = Column(Integer, ForeignKey('users.id', ondelete='CASCADE'), index=True)")
    lines.append("    created_at = Column(DateTime, default=_utcnow, index=True)")
    lines.append("    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)")
    return lines


def _models_user(spec: ProjectSpec) -> str:
    return f'''
class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(64), unique=True, index=True, nullable=False)
    display_name = Column(String(128), nullable=False, default="")
    email = Column(String(128), nullable=True)
    password_hash = Column(String(256), nullable=False)
    is_admin = Column(Boolean, default=False)
    is_banned = Column(Boolean, default=False)
    created_at = Column(DateTime, default=_utcnow)
'''


def models_code(spec: ProjectSpec) -> str:
    parts = ['''# Auto-generated by ayka-kit. Edit freely.
from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, Float, Date, JSON, ForeignKey
from app.database import Base

def _utcnow():
    return datetime.now(timezone.utc)
''']
    if spec.auth:
        parts.append(_models_user(spec))
        parts.append(N)
    for res in spec.resources.values():
        parts.append(f"class {class_name(res.name)}(Base):")
        parts.append(f"    __tablename__ = {res.table!r}")
        for line in _model_body(res, spec):
            parts.append(line)
        parts.append(N)
    return N.join(parts)


# --------------------------------------------------------------------------
# schemas.py
# --------------------------------------------------------------------------


def _out_fields(res: ResourceSpec, spec: ProjectSpec) -> List[str]:
    out = ["    id: int"]
    if spec.auth and not res.public:
        out.append("    owner_id: Optional[int] = None")
    for f in res.fields:
        if f.name in ("id", "owner_id"):
            continue
        typ = _PYD[f.kind]
        out.append(f"    {f.name}: Optional[{typ}] = None")
    out.append("    created_at: Optional[datetime] = None")
    out.append("    updated_at: Optional[datetime] = None")
    return out


def _create_fields(res: ResourceSpec) -> List[str]:
    out = []
    for f in res.fields:
        if f.name in ("id", "owner_id", "created_at", "updated_at"):
            continue
        typ = _PYD[f.kind]
        if f.kind == "password":
            typ = "str"
        out.append(f"    {f.name}: {typ}{_PYD_DEFAULT.get(f.kind, '')}")
    return out


def schemas_code(spec: ProjectSpec) -> str:
    parts = ['''# Auto-generated by ayka-kit. Edit freely.
from datetime import datetime, date
from typing import Optional, List, Any
from pydantic import BaseModel, ConfigDict
''']
    for res in spec.resources.values():
        cls = class_name(res.name)

        def build(mode: str) -> str:
            header = (
                f"class {cls}Create(BaseModel):"
                if mode == "create"
                else f"class {cls}Update(BaseModel):\n    model_config = ConfigDict()"
            )
            if mode == "create":
                fields = _create_fields(res)
            else:
                fields = []
                for f in res.fields:
                    if f.name in ("id", "owner_id", "created_at", "updated_at"):
                        continue
                    typ = _PYD[f.kind]
                    fields.append(f"    {f.name}: Optional[{typ}] = None")
                if not fields:
                    fields = ["    pass"]
            return header + N + N.join(fields)

        parts.append(build("create"))
        parts.append(N)
        parts.append(build("update"))
        parts.append(N)

        out = [f"class {cls}Out(BaseModel):"]
        out.append("    model_config = ConfigDict(from_attributes=True)")
        out.extend(_out_fields(res, spec))
        parts.append(N.join(out))
        parts.append(N)

        if spec.auth and not res.public:
            parts.append(f"class {cls}OutAdmin({cls}Out):")
            parts.append("    pass")
            parts.append(N)
    return N.join(parts)


# --------------------------------------------------------------------------
# routes.py
# --------------------------------------------------------------------------


def _resource_endpoint_defs(res: ResourceSpec, spec: ProjectSpec) -> List[str]:
    cls = class_name(res.name)
    table_var = f"models.{cls}"
    owned = spec.auth and not res.public
    out = []
    user_dep = ", user=Depends(CURRENT_USER)" if owned else ""
    owner_filter = f".filter({table_var}.owner_id == user.id)" if owned else ""

    def scope(query):
        return query if not owned else f"{query}{owner_filter}"

    def check_owner(code: str) -> str:
        return code

    def not_found_guard(var: str) -> str:
        if owned:
            return f"    if not {var} or {var}.owner_id != user.id:\n        raise HTTPException(404, 'Not found')"
        return f"    if not {var}:\n        raise HTTPException(404, 'Not found')"

    crud = res.crud
    if crud in ("read", "write", "full"):
        out.append(f"@router.get('', response_model=list[schemas.{cls}Out])")
        out.append(f"def list_{res.name}(q: Optional[str] = Query(None), limit: int = Query(50, le=200), offset: int = 0{user_dep}, db: Session = Depends(get_db)):")
        out.append(f"    query = db.query({table_var}){owner_filter}")
        if res.search:
            fields = ", ".join(repr(f) for f in res.search)
            out.append("    if q:")
            out.append(f"        conds = [getattr({table_var}, f).like('%' + q + '%') for f in [{fields}]]")
            out.append("        query = query.filter(or_(*conds))")
        out.append(f"    return query.order_by({table_var}.created_at.desc()).offset(offset).limit(limit).all()")
        out.append(N)

    if crud in ("read", "full"):
        out.append(f"@router.get('/{{item_id}}', response_model=schemas.{cls}Out)")
        out.append(f"def get_{res.name}(item_id: int{user_dep}, db: Session = Depends(get_db)):")
        out.append(f"    item = db.query({table_var}).filter({table_var}.id == item_id).first()")
        out.append(not_found_guard("item"))
        out.append("    return item")
        out.append(N)

    if crud in ("create", "write", "full"):
        out.append(f"@router.post('', response_model=schemas.{cls}Out, status_code=201)")
        out.append(f"def create_{res.name}(payload: schemas.{cls}Create{user_dep}, db: Session = Depends(get_db)):")
        if owned:
            out.append(f"    item = {table_var}(owner_id=user.id, **payload.model_dump())")
        else:
            out.append(f"    item = {table_var}(**payload.model_dump())")
        out.append("    db.add(item)")
        out.append("    db.commit()")
        out.append("    db.refresh(item)")
        out.append("    return item")
        out.append(N)

    if crud in ("write", "full"):
        out.append(f"@router.put('/{{item_id}}', response_model=schemas.{cls}Out)")
        out.append(f"def update_{res.name}(item_id: int, payload: schemas.{cls}Update{user_dep}, db: Session = Depends(get_db)):")
        out.append(f"    item = db.query({table_var}).filter({table_var}.id == item_id).first()")
        out.append(not_found_guard("item"))
        out.append("    data = payload.model_dump(exclude_unset=True)")
        out.append("    for key, value in data.items():")
        out.append("        setattr(item, key, value)")
        out.append("    db.commit()")
        out.append("    db.refresh(item)")
        out.append("    return item")
        out.append(N)

        out.append(f"@router.delete('/{{item_id}}', status_code=204)")
        out.append(f"def delete_{res.name}(item_id: int{user_dep}, db: Session = Depends(get_db)):")
        out.append(f"    item = db.query({table_var}).filter({table_var}.id == item_id).first()")
        out.append(not_found_guard("item"))
        out.append("    db.delete(item)")
        out.append("    db.commit()")
        out.append("    return None")
    return out


def routes_code(spec: ProjectSpec) -> str:
    parts = ['''# Auto-generated by ayka-kit. Edit freely.
from typing import Optional, List, Dict, Any
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from sqlalchemy import or_
from app.database import get_db
from app import models, schemas
''']

    if spec.auth:
        parts.append(f'''from ayka.auth import JwtAuth, get_current_user_dependency

AUTH = JwtAuth(
    models.User,
    get_db,
    issuer={spec.name!r},
    secret_env={env_key(spec.name, 'SECRET')!r},
    secret_file='.secret_key',
)
CURRENT_USER = get_current_user_dependency(AUTH)

routers = [AUTH.build_router()]
''')
    else:
        parts.append("\nrouters = []\n")

    for res in spec.resources.values():
        parts.append(f"router = APIRouter(prefix='/api/{res.name}', tags=[{res.name!r}])")
        parts.append(N)
        parts.extend(_resource_endpoint_defs(res, spec))
        parts.append("routers.append(router)")
        parts.append(N)

    parts.append("\n__all__ = ['routers']\n")
    return N.join(parts)


# --------------------------------------------------------------------------
# main.py
# --------------------------------------------------------------------------


def main_code(spec: ProjectSpec) -> str:
    return f'''# Auto-generated by ayka-kit. Edit freely.
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from ayka.middleware import RateLimiter, rate_limit_middleware
from app import config, models  # noqa: F401 - models must be imported to register tables
from app.database import init_db
from app.routes import routers

init_db()

app = FastAPI(title=config.TITLE, version=config.VERSION)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.add_middleware(
    rate_limit_middleware(RateLimiter(max_requests=config.RATE_LIMIT, window_seconds=config.RATE_WINDOW))
)

for router in routers:
    app.include_router(router)


@app.get("/api/health")
def health():
    return {{"status": "ok", "name": config.APP_NAME}}


@app.get("/api/version")
def version():
    return {{"name": config.APP_NAME, "version": config.VERSION}}
'''


# --------------------------------------------------------------------------
# support files
# --------------------------------------------------------------------------


def package_init() -> str:
    return ""


def run_py_code(spec: ProjectSpec) -> str:
    return f'''# Auto-generated by ayka-kit. Edit freely.
import uvicorn
from app import config

if __name__ == "__main__":
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=False)
'''


RUN_BAT = """@echo off
cd /d "%~dp0"
if not exist "venv" (
    python -m venv venv
)
call venv\\Scripts\\activate.bat
pip install -r requirements.txt -q
if not exist "data" mkdir data
echo.
echo [*] Starting...
python run.py
"""

REQUIREMENTS = """# generated by ayka-kit
fastapi>=0.100
uvicorn[standard]>=0.23
sqlalchemy>=2.0
python-jose[cryptography]>=3.3
passlib>=1.7.4
python-multipart>=0.0.9
pyyaml>=6.0
ayka-kit>=0.1
"""

GITIGNORE = """venv/
__pycache__/
*.pyc
data/
.secret_key
*.db
.pytest_cache/
.idea/
.vscode/
.DS_Store
"""


def readme_code(spec: ProjectSpec) -> str:
    try:
        from .spec import load_spec, DEFAULT_SPEC
    except ImportError:  # pragma: no cover
        pass

    lines = [
        f"# {spec.title}",
        "",
        f"Generated by **[4ayka-kit](https://github.com/krempik)** — an AI-friendly spec→FastAPI generator.",
        "",
        f"- app: `{spec.name}`",
        f"- auth: {'JWT (`/api/auth/*`)' if spec.auth else 'none'}",
        f"- db: `{spec.db_file}` (auto-migrations, data survives updates)",
        "",
        "## Run",
        "",
        "```bash",
        "pip install -r requirements.txt",
        "uvicorn app.main:app --reload   # or: python run.py",
        "```",
        "",
        "## Endpoints",
        "",
        "| Method | Path | Notes |",
        "|--------|------|-------|",
    ]
    if spec.auth:
        lines.append("| POST | `/api/auth/register` | create account, returns tokens |")
        lines.append("| POST | `/api/auth/login` | sign in |")
        lines.append("| POST | `/api/auth/refresh` | refresh tokens |")
        lines.append("| GET  | `/api/auth/me` | current user |")
    lines.append("| GET  | `/api/health` | liveness |")
    lines.append("| GET  | `/api/version` | name + version |")
    for res in spec.resources.values():
        lines.append(f"| GET/POST | `/api/{res.name}` | {res.crud} CRUD ({', '.join(f.name for f in res.fields)}) |")
        if res.crud in ("write", "full"):
            lines.append(f"| PUT/DELETE | `/api/{res.name}/{{id}}` | update / remove |")
    lines.extend([
        "",
        "## Regenerate",
        "",
        "Edit `spec.yaml`, then run `ayka gen` and restart the server.",
        "",
        "## Test",
        "",
        "```bash",
        "python -m pytest",
        "```",
        "",
    ])
    return "\n".join(lines)


def tests_code(spec: ProjectSpec) -> str:
    env_db = env_key(spec.name, "DB")
    lines = [
        "# Auto-generated by ayka-kit. Edit freely.",
        "import os",
        "import tempfile",
        f"os.environ.setdefault({env_db!r}, os.path.join(tempfile.gettempdir(), 'ayka_test_' + {spec.name!r} + '.db'))",
        f"if os.path.exists(os.environ[{env_db!r}]):",
        f"    os.remove(os.environ[{env_db!r}])",
        "from fastapi.testclient import TestClient",
        "from app.main import app",
        "",
        "client = TestClient(app)",
        "",
        "",
        "def test_health():",
        "    r = client.get('/api/health')",
        "    assert r.status_code == 200",
        "",
        "",
        "def test_version():",
        "    r = client.get('/api/version')",
        "    assert r.status_code == 200",
        "    assert 'version' in r.json()",
        "",
    ]
    if spec.auth:
        lines += [
            "",
            "def test_auth_register():",
            "    r = client.post('/api/auth/register',",
            "                     json={'username': 'alice', 'password': 'supersecret', 'display_name': 'Alice'})",
            "    assert r.status_code == 201, r.text",
            "    assert 'access_token' in r.json()",
            "",
            "",
            "def test_resource_crud():",
            "    token = client.post('/api/auth/register',",
            "                          json={'username': 'bob', 'password': 'supersecret', 'display_name': 'Bob'}).json()['access_token']",
            "    h = {'Authorization': 'Bearer ' + token}",
        ]
    for res in spec.resources.values():
        payload = _test_payload(res)
        hdr = "h" if spec.auth else "{}"
        create_ok = res.crud in ("create", "write", "full")
        list_ok = res.crud in ("read", "write", "full")
        if create_ok:
            lines.append(f"    r = client.post('/api/{res.name}', headers={hdr}, json={{ {payload} }})")
            lines.append("    assert r.status_code == 201, r.text")
        if list_ok:
            lines.append(f"    r = client.get('/api/{res.name}', headers={hdr})")
            check = "r.status_code == 200 and len(r.json()) >= 1" if create_ok else "r.status_code == 200"
            lines.append(f"    assert {check}")
    if spec.auth:
        lines.append("")
    return "\n".join(lines)


def _test_payload(res: ResourceSpec) -> str:
    parts = []
    for f in res.fields:
        if f.kind in ("list",):
            parts.append(f"'{f.name}': []")
        elif f.kind == "bool":
            parts.append(f"'{f.name}': True")
        elif f.kind == "int":
            parts.append(f"'{f.name}': 1")
        elif f.kind == "float":
            parts.append(f"'{f.name}': 1.0")
        elif f.kind == "date":
            parts.append(f"'{f.name}': '2026-01-01'")
        elif f.kind == "datetime":
            parts.append(f"'{f.name}': '2026-01-01T00:00:00'")
        elif f.kind == "json":
            parts.append(f"'{f.name}': {{}}")
        else:
            parts.append(f"'{f.name}': 'x'")
    return ", ".join(parts)


def ci_code(spec: ProjectSpec) -> str:
    return f"""name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: python -m pip install -r requirements.txt
      - run: python -m pytest
"""