"""Scaffold starter projects: fastapi (spec + generated app) or web game."""
import os
import shutil
from pathlib import Path
from typing import List

from .generator import DEFAULT_SPEC, generate, load_project

GAME_INDEX = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div id="hud">
    <span id="score">0</span>
  </div>
  <canvas id="game" width="640" height="400"></canvas>
  <script src="main.js"></script>
</body>
</html>
"""

GAME_STYLE = """/* {title} - generated by ayka-kit */
body {
  margin: 0;
  min-height: 100vh;
  display: grid;
  place-items: center;
  background: #0e1116;
  color: #e8eaf0;
  font-family: system-ui, sans-serif;
}

#hud {
  position: fixed;
  top: 12px;
  left: 16px;
  font-size: 20px;
  letter-spacing: 2px;
}

canvas {
  background: #161b22;
  border: 1px solid #2a3240;
  border-radius: 8px;
  image-rendering: pixelated;
}
"""

GAME_JS = """/* {title} - generated by ayka-kit
 * Tiny skeleton: input, update, render loop. Make it yours.
 */
const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const scoreEl = document.getElementById('score');

const state = {
  x: canvas.width / 2,
  y: canvas.height / 2,
  keys: new Set(),
  score: 0,
};

window.addEventListener('keydown', (e) => state.keys.add(e.key));
window.addEventListener('keyup', (e) => state.keys.delete(e.key));

function update(dt) {
  const speed = 200 * dt;
  if (state.keys.has('ArrowLeft') || state.keys.has('a')) state.x -= speed;
  if (state.keys.has('ArrowRight') || state.keys.has('d')) state.x += speed;
  if (state.keys.has('ArrowUp') || state.keys.has('w')) state.y -= speed;
  if (state.keys.has('ArrowDown') || state.keys.has('s')) state.y += speed;

  state.x = Math.max(8, Math.min(canvas.width - 8, state.x));
  state.y = Math.max(8, Math.min(canvas.height - 8, state.y));
}

function draw() {
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = '#4ade80';
  ctx.fillRect(state.x - 8, state.y - 8, 16, 16);
  scoreEl.textContent = state.score;
}

let last = performance.now();
function frame(now) {
  const dt = Math.min((now - last) / 1000, 0.05);
  last = now;
  update(dt);
  draw();
  requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
"""

FASTAPI_README = """# {title}

Generated with `ayka new fastapi {name}`.

## Get started

    pip install -e <path-to-4ayka-kit>   # or: pip install ayka-kit
    ayka gen
    python run.py                        # http://localhost:8000  (docs at /docs)

Edit `spec.yaml` and re-run `ayka gen` to regenerate the API.
"""


def _write(path: Path, content: str) -> None:
    if path.exists():
        raise FileExistsError(f"{path} already exists — refusing to overwrite")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def scaffold_fastapi(name: str, target: str) -> List[str]:
    target = Path(target)
    project_name = name.lower().replace(" ", "-")
    spec_text = DEFAULT_SPEC.replace("project:\n  name: notes", f"project:\n  name: {project_name}")
    all_files = []
    for rel, content in [
        ("spec.yaml", spec_text),
        ("README.md", FASTAPI_README.format(title=project_name.title(), name=project_name)),
        ("run.bat", _RUN_BAT),
        (".gitignore", _GITIGNORE),
    ]:
        _write(target / rel, content)
        all_files.append(rel)
    return all_files


def scaffold_game(title: str, target: str) -> List[str]:
    target = Path(target)
    files = {
        "index.html": GAME_INDEX.replace("{title}", title),
        "style.css": GAME_STYLE.replace("{title}", title),
        "main.js": GAME_JS.replace("{title}", title),
    }
    all_files = []
    for rel, content in files.items():
        _write(target / rel, content)
        all_files.append(rel)
    return all_files


_RUN_BAT = """@echo off
cd /d "%~dp0"
if not exist "venv" (
    python -m venv venv
)
call venv\\Scripts\\activate.bat
if not exist "requirements.txt" (
    pip install ayka-kit -q
)
echo.
echo [*] ayka gen ...
ayka gen
echo [*] Starting...
python run.py
"""

_GITIGNORE = """venv/
__pycache__/
*.pyc
data/
.secret_key
*.db
.pytest_cache/
.idea/
.vscode/
.DS_Store
"""


TEMPLATES = {
    "fastapi": ("ayka new fastapi <name>", scaffold_fastapi),
    "game": ("ayka new game <title>", scaffold_game),
}


__all__ = ["TEMPLATES", "scaffold_fastapi", "scaffold_game"]